import { CityObject } from "./types";

export const CitiesPlaka = [
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Amasya",
  "Ankara",
  "Antalya",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Isparta",
  "Mersin",
  "İstanbul",
  "İzmir",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Kahramanmaraş",
  "Mardin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Şanlıurfa",
  "Uşak",
  "Van",
  "Yozgat",
  "Zonguldak",
  "Aksaray",
  "Bayburt",
  "Karaman",
  "Kırıkkale",
  "Batman",
  "Şırnak",
  "Bartın",
  "Ardahan",
  "Iğdır",
  "Yalova",
  "Karabük",
  "Kilis",
  "Osmaniye",
  "Düzce",
];

export const CitiesLexiographic = {
  Adana: 1,
  Adıyaman: 2,
  Afyonkarahisar: 3,
  Ağrı: 4,
  Aksaray: 5,
  Amasya: 6,
  Ankara: 7,
  Antalya: 8,
  Ardahan: 9,
  Artvin: 10,
  Aydın: 11,
  Balıkesir: 12,
  Bartın: 13,
  Batman: 14,
  Bayburt: 15,
  Bilecik: 16,
  Bingöl: 17,
  Bitlis: 18,
  Bolu: 19,
  Burdur: 20,
  Bursa: 21,
  Çanakkale: 22,
  Çankırı: 23,
  Çorum: 24,
  Denizli: 25,
  Diyarbakır: 26,
  Düzce: 27,
  Edirne: 28,
  Elazığ: 29,
  Erzincan: 30,
  Erzurum: 31,
  Eskişehir: 32,
  Gaziantep: 33,
  Giresun: 34,
  Gümüşhane: 35,
  Hakkari: 36,
  Hatay: 37,
  Iğdır: 38,
  Isparta: 39,
  İstanbul: 40,
  İzmir: 41,
  Kahramanmaraş: 42,
  Karabük: 43,
  Karaman: 44,
  Kars: 45,
  Kastamonu: 46,
  Kayseri: 47,
  Kırıkkale: 48,
  Kırklareli: 49,
  Kırşehir: 50,
  Kilis: 51,
  Kocaeli: 52,
  Konya: 53,
  Kütahya: 54,
  Malatya: 55,
  Manisa: 56,
  Mardin: 57,
  Mersin: 58,
  Muğla: 59,
  Muş: 60,
  Nevşehir: 61,
  Niğde: 62,
  Ordu: 63,
  Osmaniye: 64,
  Rize: 65,
  Sakarya: 66,
  Samsun: 67,
  Siirt: 68,
  Sinop: 69,
  Sivas: 70,
  Şanlıurfa: 71,
  Şırnak: 72,
  Tekirdağ: 73,
  Tokat: 74,
  Trabzon: 75,
  Tunceli: 76,
  Uşak: 77,
  Yalova: 78,
  Van: 79,
  Yozgat: 80,
  Zonguldak: 81,
};

export const CityObjects: CityObject[] = [
  {
    name: "Adana",
    start: 2,
    num_of_districts: 15,
    districts: [
      "Aladağ",
      "Ceyhan",
      "Çukurova",
      "Feke",
      "İmamoğlu",
      "Karaisalı",
      "Karataş",
      "Kozan",
      "Pozantı",
      "Saimbeyli",
      "Sarıçam",
      "Seyhan",
      "Tufanbeyli",
      "Yumurtalık",
      "Yüreğir",
    ],
  },
  {
    name: "Adıyaman",
    start: 18,
    num_of_districts: 9,
    districts: [
      "Merkez",
      "Besni",
      "Çelikhan",
      "Gerger",
      "Gölbaşı / Adıyaman",
      "Kahta",
      "Samsat",
      "Sincik",
      "Tut",
    ],
  },
  {
    name: "Afyonkarahisar",
    start: 28,
    num_of_districts: 18,
    districts: [
      "Merkez",
      "Başmakçı",
      "Bayat / Afyonkarahisar",
      "Bolvadin",
      "Çay",
      "Çobanlar",
      "Dazkırı",
      "Dinar",
      "Emirdağ",
      "Evciler",
      "Hocalar",
      "İhsaniye",
      "İscehisar",
      "Kızılören",
      "Sandıklı",
      "Sinanpaşa",
      "Sultandağı",
      "Şuhut",
    ],
  },
  {
    name: "Ağrı",
    start: 47,
    num_of_districts: 8,
    districts: [
      "Merkez",
      "Diyadin",
      "Doğubayazıt",
      "Eleşkirt",
      "Hamur",
      "Patnos",
      "Taşlıçay",
      "Tutak",
    ],
  },
  {
    name: "Aksaray",
    start: 56,
    num_of_districts: 7,
    districts: [
      "Merkez",
      "Ağaçören",
      "Eskil",
      "Gülağaç",
      "Güzelyurt",
      "Ortaköy / Aksaray",
      "Sarıyahşi",
    ],
  },
  {
    name: "Amasya",
    start: 64,
    num_of_districts: 7,
    districts: [
      "Merkez",
      "Göynücek",
      "Gümüşhacıköy",
      "Hamamözü",
      "Merzifon",
      "Suluova",
      "Taşova",
    ],
  },
  {
    name: "Ankara",
    start: 72,
    num_of_districts: 25,
    districts: [
      "Akyurt",
      "Altındağ",
      "Ayaş",
      "Bala",
      "Beypazarı",
      "Çamlıdere",
      "Çankaya",
      "Çubuk",
      "Elmadağ",
      "Etimesgut",
      "Evren",
      "Gölbaşı / Ankara",
      "Güdül",
      "Haymana",
      "Kalecik",
      "Kazan",
      "Keçiören",
      "Kızılcahamam",
      "Mamak",
      "Nallıhan",
      "Polatlı",
      "Pursaklar",
      "Sincan",
      "Şereflikoçhisar",
      "Yenimahalle",
    ],
  },
  {
    name: "Antalya",
    start: 98,
    num_of_districts: 19,
    districts: [
      "Akseki",
      "Aksu / Antalya",
      "Alanya",
      "Demre",
      "Döşemealtı",
      "Elmalı",
      "Finike",
      "Gazipaşa",
      "Gündoğmuş",
      "İbradı",
      "Kaş",
      "Kemer / Antalya",
      "Kepez",
      "Konyaaltı",
      "Korkuteli",
      "Kumluca",
      "Manavgat",
      "Muratpaşa",
      "Serik",
    ],
  },
  {
    name: "Ardahan",
    start: 118,
    num_of_districts: 6,
    districts: ["Merkez", "Çıldır", "Damal", "Göle", "Hanak", "Posof"],
  },
  {
    name: "Artvin",
    start: 125,
    num_of_districts: 8,
    districts: [
      "Merkez",
      "Ardanuç",
      "Arhavi",
      "Borçka",
      "Hopa",
      "Murgul",
      "Şavşat",
      "Yusufeli",
    ],
  },
  {
    name: "Aydın",
    start: 134,
    num_of_districts: 17,
    districts: [
      "Bozdoğan",
      "Buharkent",
      "Çine",
      "Didim",
      "Efeler",
      "Germencik",
      "İncirliova",
      "Karacasu",
      "Karpuzlu",
      "Koçarlı",
      "Köşk",
      "Kuşadası",
      "Kuyucak",
      "Nazilli",
      "Söke",
      "Sultanhisar",
      "Yenipazar / Aydın",
    ],
  },
  {
    name: "Balıkesir",
    start: 152,
    num_of_districts: 20,
    districts: [
      "Altıeylül",
      "Ayvalık",
      "Balya",
      "Bandırma",
      "Bigadiç",
      "Burhaniye",
      "Dursunbey",
      "Edremit / Balıkesir",
      "Erdek",
      "Gömeç",
      "Gönen / Balıkesir",
      "Havran",
      "İvrindi",
      "Karesi",
      "Kepsut",
      "Manyas",
      "Marmara",
      "Savaştepe",
      "Sındırgı",
      "Susurluk",
    ],
  },
  {
    name: "Bartın",
    start: 173,
    num_of_districts: 4,
    districts: ["Merkez", "Amasra", "Kurucaşile", "Ulus"],
  },
  {
    name: "Batman",
    start: 178,
    num_of_districts: 6,
    districts: ["Merkez", "Beşiri", "Gercüş", "Hasankeyf", "Kozluk", "Sason"],
  },
  {
    name: "Bayburt",
    start: 185,
    num_of_districts: 3,
    districts: ["Merkez", "Aydıntepe", "Demirözü"],
  },
  {
    name: "Bilecik",
    start: 189,
    num_of_districts: 8,
    districts: [
      "Merkez",
      "Bozüyük",
      "Gölpazarı",
      "İnhisar",
      "Osmaneli",
      "Pazaryeri",
      "Söğüt",
      "Yenipazar / Bilecik",
    ],
  },
  {
    name: "Bingöl",
    start: 198,
    num_of_districts: 8,
    districts: [
      "Merkez",
      "Adaklı",
      "Genç",
      "Karlıova",
      "Kiğı",
      "Solhan",
      "Yayladere",
      "Yedisu",
    ],
  },
  {
    name: "Bitlis",
    start: 207,
    num_of_districts: 7,
    districts: [
      "Merkez",
      "Adilcevaz",
      "Ahlat",
      "Güroymak",
      "Hizan",
      "Mutki",
      "Tatvan",
    ],
  },
  {
    name: "Bolu",
    start: 215,
    num_of_districts: 9,
    districts: [
      "Merkez",
      "Dörtdivan",
      "Gerede",
      "Göynük",
      "Kıbrıscık",
      "Mengen",
      "Mudurnu",
      "Seben",
      "Yeniçağa",
    ],
  },
  {
    name: "Burdur",
    start: 225,
    num_of_districts: 11,
    districts: [
      "Merkez",
      "Ağlasun",
      "Altınyayla / Burdur",
      "Bucak",
      "Çavdır",
      "Çeltikçi",
      "Gölhisar",
      "Karamanlı",
      "Kemer / Burdur",
      "Tefenni",
      "Yeşilova",
    ],
  },
  {
    name: "Bursa",
    start: 237,
    num_of_districts: 17,
    districts: [
      "Büyükorhan",
      "Gemlik",
      "Gürsu",
      "Harmancık",
      "İnegöl",
      "İznik",
      "Karacabey",
      "Keles",
      "Kestel",
      "Mudanya",
      "Mustafakemalpaşa",
      "Nilüfer",
      "Orhaneli",
      "Orhangazi",
      "Osmangazi",
      "Yenişehir / Bursa",
      "Yıldırım",
    ],
  },
  {
    name: "Çanakkale",
    start: 255,
    num_of_districts: 12,
    districts: [
      "Merkez",
      "Ayvacık / Çanakkale",
      "Bayramiç",
      "Biga",
      "Bozcaada",
      "Çan",
      "Eceabat",
      "Ezine",
      "Gelibolu",
      "Gökçeada",
      "Lapseki",
      "Yenice / Çanakkale",
    ],
  },
  {
    name: "Çankırı",
    start: 268,
    num_of_districts: 12,
    districts: [
      "Merkez",
      "Atkaracalar",
      "Bayramören",
      "Çerkeş",
      "Eldivan",
      "Ilgaz",
      "Kızılırmak",
      "Korgun",
      "Kurşunlu",
      "Orta",
      "Şabanözü",
      "Yapraklı",
    ],
  },
  {
    name: "Çorum",
    start: 281,
    num_of_districts: 14,
    districts: [
      "Merkez",
      "Alaca",
      "Bayat / Çorum",
      "Boğazkale",
      "Dodurga",
      "İskilip",
      "Kargı",
      "Laçin",
      "Mecitözü",
      "Oğuzlar",
      "Ortaköy / Çorum",
      "Osmancık",
      "Sungurlu",
      "Uğurludağ",
    ],
  },
  {
    name: "Denizli",
    start: 296,
    num_of_districts: 19,
    districts: [
      "Acıpayam",
      "Babadağ",
      "Baklan",
      "Bekilli",
      "Beyağaç",
      "Bozkurt / Denizli",
      "Buldan",
      "Çal",
      "Çameli",
      "Çardak",
      "Çivril",
      "Güney",
      "Honaz",
      "Kale / Denizli",
      "Merkezefendi",
      "Pamukkale",
      "Sarayköy",
      "Serinhisar",
      "Tavas",
    ],
  },
  {
    name: "Diyarbakır",
    start: 316,
    num_of_districts: 17,
    districts: [
      "Bağlar",
      "Bismil",
      "Çermik",
      "Çınar",
      "Çüngüş",
      "Dicle",
      "Eğil",
      "Ergani",
      "Hani",
      "Hazro",
      "Kayapınar",
      "Kocaköy",
      "Kulp",
      "Lice",
      "Silvan",
      "Sur",
      "Yenişehir / Diyarbakır",
    ],
  },
  {
    name: "Düzce",
    start: 334,
    num_of_districts: 8,
    districts: [
      "Merkez",
      "Akçakoca",
      "Cumayeri",
      "Çilimli",
      "Gölyaka",
      "Gümüşova",
      "Kaynaşlı",
      "Yığılca",
    ],
  },
  {
    name: "Edirne",
    start: 343,
    num_of_districts: 9,
    districts: [
      "Merkez",
      "Enez",
      "Havsa",
      "İpsala",
      "Keşan",
      "Lalapaşa",
      "Meriç",
      "Süloğlu",
      "Uzunköprü",
    ],
  },
  {
    name: "Elazığ",
    start: 353,
    num_of_districts: 11,
    districts: [
      "Merkez",
      "Ağın",
      "Alacakaya",
      "Arıcak",
      "Baskil",
      "Karakoçan",
      "Keban",
      "Kovancılar",
      "Maden",
      "Palu",
      "Sivrice",
    ],
  },
  {
    name: "Erzincan",
    start: 365,
    num_of_districts: 9,
    districts: [
      "Merkez",
      "Çayırlı",
      "İliç",
      "Kemah",
      "Kemaliye",
      "Otlukbeli",
      "Refahiye",
      "Tercan",
      "Üzümlü",
    ],
  },
  {
    name: "Erzurum",
    start: 375,
    num_of_districts: 20,
    districts: [
      "Aşkale",
      "Aziziye",
      "Çat",
      "Hınıs",
      "Horasan",
      "İspir",
      "Karaçoban",
      "Karayazı",
      "Köprüköy",
      "Narman",
      "Oltu",
      "Olur",
      "Palandöken",
      "Pasinler",
      "Pazaryolu",
      "Şenkaya",
      "Tekman",
      "Tortum",
      "Uzundere",
      "Yakutiye",
    ],
  },
  {
    name: "Eskişehir",
    start: 396,
    num_of_districts: 14,
    districts: [
      "Alpu",
      "Beylikova",
      "Çifteler",
      "Günyüzü",
      "Han",
      "İnönü",
      "Mahmudiye",
      "Mihalgazi",
      "Mihalıççık",
      "Odunpazarı",
      "Sarıcakaya",
      "Seyitgazi",
      "Sivrihisar",
      "Tepebaşı",
    ],
  },
  {
    name: "Gaziantep",
    start: 411,
    num_of_districts: 9,
    districts: [
      "Araban",
      "İslahiye",
      "Karkamış",
      "Nizip",
      "Nurdağı",
      "Oğuzeli",
      "Şahinbey",
      "Şehitkamil",
      "Yavuzeli",
    ],
  },
  {
    name: "Giresun",
    start: 421,
    num_of_districts: 16,
    districts: [
      "Merkez",
      "Alucra",
      "Bulancak",
      "Çamoluk",
      "Çanakçı",
      "Dereli",
      "Doğankent",
      "Espiye",
      "Eynesil",
      "Görele",
      "Güce",
      "Keşap",
      "Piraziz",
      "Şebinkarahisar",
      "Tirebolu",
      "Yağlıdere",
    ],
  },
  {
    name: "Gümüşhane",
    start: 438,
    num_of_districts: 6,
    districts: ["Merkez", "Kelkit", "Köse", "Kürtün", "Şiran", "Torul"],
  },
  {
    name: "Hakkari",
    start: 445,
    num_of_districts: 4,
    districts: ["Merkez", "Çukurca", "Şemdinli", "Yüksekova"],
  },
  {
    name: "Hatay",
    start: 450,
    num_of_districts: 15,
    districts: [
      "Altınözü",
      "Antakya",
      "Arsuz",
      "Belen",
      "Defne",
      "Dörtyol",
      "Erzin",
      "Hassa",
      "İskenderun",
      "Kırıkhan",
      "Kumlu",
      "Payas",
      "Reyhanlı",
      "Samandağ",
      "Yayladağı",
    ],
  },
  {
    name: "Iğdır",
    start: 466,
    num_of_districts: 4,
    districts: ["Merkez", "Aralık", "Karakoyunlu", "Tuzluca"],
  },
  {
    name: "Isparta",
    start: 471,
    num_of_districts: 13,
    districts: [
      "Merkez",
      "Aksu / Isparta",
      "Atabey",
      "Eğirdir",
      "Gelendost",
      "Gönen / Isparta",
      "Keçiborlu",
      "Senirkent",
      "Sütçüler",
      "Şarkikaraağaç",
      "Uluborlu",
      "Yalvaç",
      "Yenişarbademli",
    ],
  },
  {
    name: "İstanbul",
    start: 485,
    num_of_districts: 39,
    districts: [
      "Adalar",
      "Arnavutköy",
      "Ataşehir",
      "Avcılar",
      "Bağcılar",
      "Bahçelievler",
      "Bakırköy",
      "Başakşehir",
      "Bayrampaşa",
      "Beşiktaş",
      "Beykoz",
      "Beylikdüzü",
      "Beyoğlu",
      "Büyükçekmece",
      "Çatalca",
      "Çekmeköy",
      "Esenler",
      "Esenyurt",
      "Eyüp",
      "Fatih",
      "Gaziosmanpaşa",
      "Güngören",
      "Kadıköy",
      "Kağıthane",
      "Kartal",
      "Küçükçekmece",
      "Maltepe",
      "Pendik",
      "Sancaktepe",
      "Sarıyer",
      "Silivri",
      "Sultanbeyli",
      "Sultangazi",
      "Şile",
      "Şişli",
      "Tuzla",
      "Ümraniye",
      "Üsküdar",
      "Zeytinburnu",
    ],
  },
  {
    name: "İzmir",
    start: 525,
    num_of_districts: 30,
    districts: [
      "Aliağa",
      "Balçova",
      "Bayındır",
      "Bayraklı",
      "Bergama",
      "Beydağ",
      "Bornova",
      "Buca",
      "Çeşme",
      "Çiğli",
      "Dikili",
      "Foça",
      "Gaziemir",
      "Güzelbahçe",
      "Karabağlar",
      "Karaburun",
      "Karşıyaka",
      "Kemalpaşa / İzmir",
      "Kınık",
      "Kiraz",
      "Konak",
      "Menderes",
      "Menemen",
      "Narlıdere",
      "Ödemiş",
      "Seferihisar",
      "Selçuk",
      "Tire",
      "Torbalı",
      "Urla",
    ],
  },
  {
    name: "Kahramanmaraş",
    start: 556,
    num_of_districts: 11,
    districts: [
      "Afşin",
      "Andırın",
      "Çağlayancerit",
      "Dulkadiroğlu",
      "Ekinözü",
      "Elbistan",
      "Göksun",
      "Nurhak",
      "Onikişubat",
      "Pazarcık",
      "Türkoğlu",
    ],
  },
  {
    name: "Karabük",
    start: 568,
    num_of_districts: 6,
    districts: [
      "Merkez",
      "Eflani",
      "Eskipazar",
      "Ovacık / Karabük",
      "Safranbolu",
      "Yenice / Karabük",
    ],
  },
  {
    name: "Karaman",
    start: 575,
    num_of_districts: 6,
    districts: [
      "Merkez",
      "Ayrancı",
      "Başyayla",
      "Ermenek",
      "Kazımkarabekir",
      "Sarıveliler",
    ],
  },
  {
    name: "Kars",
    start: 582,
    num_of_districts: 8,
    districts: [
      "Merkez",
      "Akyaka",
      "Arpaçay",
      "Digor",
      "Kağızman",
      "Sarıkamış",
      "Selim",
      "Susuz",
    ],
  },
  {
    name: "Kastamonu",
    start: 591,
    num_of_districts: 20,
    districts: [
      "Merkez",
      "Abana",
      "Ağlı",
      "Araç",
      "Azdavay",
      "Bozkurt / Kastamonu",
      "Cide",
      "Çatalzeytin",
      "Daday",
      "Devrekani",
      "Doğanyurt",
      "Hanönü",
      "İhsangazi",
      "İnebolu",
      "Küre",
      "Pınarbaşı / Kastamonu",
      "Seydiler",
      "Şenpazar",
      "Taşköprü",
      "Tosya",
    ],
  },
  {
    name: "Kayseri",
    start: 612,
    num_of_districts: 16,
    districts: [
      "Akkışla",
      "Bünyan",
      "Develi",
      "Felahiye",
      "Hacılar",
      "İncesu",
      "Kocasinan",
      "Melikgazi",
      "Özvatan",
      "Pınarbaşı / Kayseri",
      "Sarıoğlan",
      "Sarız",
      "Talas",
      "Tomarza",
      "Yahyalı",
      "Yeşilhisar",
    ],
  },
  {
    name: "Kırıkkale",
    start: 629,
    num_of_districts: 9,
    districts: [
      "Merkez",
      "Bahşili",
      "Balışeyh",
      "Çelebi",
      "Delice",
      "Karakeçili",
      "Keskin",
      "Sulakyurt",
      "Yahşihan",
    ],
  },
  {
    name: "Kırklareli",
    start: 639,
    num_of_districts: 8,
    districts: [
      "Merkez",
      "Babaeski",
      "Demirköy",
      "Kofçaz",
      "Lüleburgaz",
      "Pehlivanköy",
      "Pınarhisar",
      "Vize",
    ],
  },
  {
    name: "Kırşehir",
    start: 648,
    num_of_districts: 7,
    districts: [
      "Merkez",
      "Akçakent",
      "Akpınar",
      "Boztepe",
      "Çiçekdağı",
      "Kaman",
      "Mucur",
    ],
  },
  {
    name: "Kilis",
    start: 656,
    num_of_districts: 4,
    districts: ["Merkez", "Elbeyli", "Musabeyli", "Polateli"],
  },
  {
    name: "Kocaeli",
    start: 661,
    num_of_districts: 12,
    districts: [
      "Başiskele",
      "Çayırova",
      "Darıca",
      "Derince",
      "Dilovası",
      "Gebze",
      "Gölcük",
      "İzmit",
      "Kandıra",
      "Karamürsel",
      "Kartepe",
      "Körfez",
    ],
  },
  {
    name: "Konya",
    start: 674,
    num_of_districts: 31,
    districts: [
      "Ahırlı",
      "Akören",
      "Akşehir",
      "Altınekin",
      "Beyşehir",
      "Bozkır",
      "Cihanbeyli",
      "Çeltik",
      "Çumra",
      "Derbent",
      "Derebucak",
      "Doğanhisar",
      "Emirgazi",
      "Ereğli / Konya",
      "Güneysınır",
      "Hadim",
      "Halkapınar",
      "Hüyük",
      "Ilgın",
      "Kadınhanı",
      "Karapınar",
      "Karatay",
      "Kulu",
      "Meram",
      "Sarayönü",
      "Selçuklu",
      "Seydişehir",
      "Taşkent",
      "Tuzlukçu",
      "Yalıhüyük",
      "Yunak",
    ],
  },
  {
    name: "Kütahya",
    start: 706,
    num_of_districts: 13,
    districts: [
      "Merkez",
      "Altıntaş",
      "Aslanapa",
      "Çavdarhisar",
      "Domaniç",
      "Dumlupınar",
      "Emet",
      "Gediz",
      "Hisarcık",
      "Pazarlar",
      "Simav",
      "Şaphane",
      "Tavşanlı",
    ],
  },
  {
    name: "Malatya",
    start: 720,
    num_of_districts: 13,
    districts: [
      "Akçadağ",
      "Arapgir",
      "Arguvan",
      "Battalgazi",
      "Darende",
      "Doğanşehir",
      "Doğanyol",
      "Hekimhan",
      "Kale / Malatya",
      "Kuluncak",
      "Pütürge",
      "Yazıhan",
      "Yeşilyurt / Malatya",
    ],
  },
  {
    name: "Manisa",
    start: 734,
    num_of_districts: 17,
    districts: [
      "Ahmetli",
      "Akhisar",
      "Alaşehir",
      "Demirci",
      "Gölmarmara",
      "Gördes",
      "Kırkağaç",
      "Köprübaşı / Manisa",
      "Kula",
      "Salihli",
      "Sarıgöl",
      "Saruhanlı",
      "Selendi",
      "Soma",
      "Şehzadeler",
      "Turgutlu",
      "Yunusemre",
    ],
  },
  {
    name: "Mardin",
    start: 752,
    num_of_districts: 10,
    districts: [
      "Artuklu",
      "Dargeçit",
      "Derik",
      "Kızıltepe",
      "Mazıdağı",
      "Midyat",
      "Nusaybin",
      "Ömerli",
      "Savur",
      "Yeşilli",
    ],
  },
  {
    name: "Mersin",
    start: 763,
    num_of_districts: 13,
    districts: [
      "Akdeniz",
      "Anamur",
      "Aydıncık / Mersin",
      "Bozyazı",
      "Çamlıyayla",
      "Erdemli",
      "Gülnar",
      "Mezitli",
      "Mut",
      "Silifke",
      "Tarsus",
      "Toroslar",
      "Yenişehir / Mersin",
    ],
  },
  {
    name: "Muğla",
    start: 777,
    num_of_districts: 13,
    districts: [
      "Bodrum",
      "Dalaman",
      "Datça",
      "Fethiye",
      "Kavaklıdere",
      "Köyceğiz",
      "Marmaris",
      "Menteşe",
      "Milas",
      "Ortaca",
      "Seydikemer",
      "Ula",
      "Yatağan",
    ],
  },
  {
    name: "Muş",
    start: 791,
    num_of_districts: 6,
    districts: ["Merkez", "Bulanık", "Hasköy", "Korkut", "Malazgirt", "Varto"],
  },
  {
    name: "Nevşehir",
    start: 798,
    num_of_districts: 8,
    districts: [
      "Merkez",
      "Acıgöl",
      "Avanos",
      "Derinkuyu",
      "Gülşehir",
      "Hacıbektaş",
      "Kozaklı",
      "Ürgüp",
    ],
  },
  {
    name: "Niğde",
    start: 807,
    num_of_districts: 6,
    districts: [
      "Merkez",
      "Altunhisar",
      "Bor",
      "Çamardı",
      "Çiftlik",
      "Ulukışla",
    ],
  },
  {
    name: "Ordu",
    start: 814,
    num_of_districts: 19,
    districts: [
      "Akkuş",
      "Altınordu",
      "Aybastı",
      "Çamaş",
      "Çatalpınar",
      "Çaybaşı",
      "Fatsa",
      "Gölköy",
      "Gülyalı",
      "Gürgentepe",
      "İkizce",
      "Kabadüz",
      "Kabataş",
      "Korgan",
      "Kumru",
      "Mesudiye",
      "Perşembe",
      "Ulubey / Ordu",
      "Ünye",
    ],
  },
  {
    name: "Osmaniye",
    start: 834,
    num_of_districts: 7,
    districts: [
      "Merkez",
      "Bahçe",
      "Düziçi",
      "Hasanbeyli",
      "Kadirli",
      "Sumbas",
      "Toprakkale",
    ],
  },
  {
    name: "Rize",
    start: 842,
    num_of_districts: 12,
    districts: [
      "Merkez",
      "Ardeşen",
      "Çamlıhemşin",
      "Çayeli",
      "Derepazarı",
      "Fındıklı",
      "Güneysu",
      "Hemşin",
      "İkizdere",
      "İyidere",
      "Kalkandere",
      "Pazar / Rize",
    ],
  },
  {
    name: "Sakarya",
    start: 855,
    num_of_districts: 16,
    districts: [
      "Adapazarı",
      "Akyazı",
      "Arifiye",
      "Erenler",
      "Ferizli",
      "Geyve",
      "Hendek",
      "Karapürçek",
      "Karasu",
      "Kaynarca",
      "Kocaali",
      "Pamukova",
      "Sapanca",
      "Serdivan",
      "Söğütlü",
      "Taraklı",
    ],
  },
  {
    name: "Samsun",
    start: 872,
    num_of_districts: 17,
    districts: [
      "19 Mayıs",
      "Alaçam",
      "Asarcık",
      "Atakum",
      "Ayvacık / Samsun",
      "Bafra",
      "Canik",
      "Çarşamba",
      "Havza",
      "İlkadım",
      "Kavak",
      "Ladik",
      "Salıpazarı",
      "Tekkeköy",
      "Terme",
      "Yakakent",
      "Vezirköprü",
    ],
  },
  {
    name: "Siirt",
    start: 890,
    num_of_districts: 7,
    districts: [
      "Merkez",
      "Baykan",
      "Eruh",
      "Kurtalan",
      "Pervari",
      "Şirvan",
      "Tillo",
    ],
  },
  {
    name: "Sinop",
    start: 898,
    num_of_districts: 9,
    districts: [
      "Merkez",
      "Ayancık",
      "Boyabat",
      "Dikmen",
      "Durağan",
      "Erfelek",
      "Gerze",
      "Saraydüzü",
      "Türkeli",
    ],
  },
  {
    name: "Sivas",
    start: 908,
    num_of_districts: 17,
    districts: [
      "Merkez",
      "Akıncılar",
      "Altınyayla / Sivas",
      "Divriği",
      "Doğanşar",
      "Gemerek",
      "Gölova",
      "Gürün",
      "Hafik",
      "İmranlı",
      "Kangal",
      "Koyulhisar",
      "Suşehri",
      "Şarkışla",
      "Ulaş",
      "Yıldızeli",
      "Zara",
    ],
  },
  {
    name: "Şanlıurfa",
    start: 926,
    num_of_districts: 13,
    districts: [
      "Akçakale",
      "Birecik",
      "Bozova",
      "Ceylanpınar",
      "Eyyübiye",
      "Halfeti",
      "Haliliye",
      "Harran",
      "Hilvan",
      "Karaköprü",
      "Siverek",
      "Suruç",
      "Viranşehir",
    ],
  },
  {
    name: "Şırnak",
    start: 940,
    num_of_districts: 7,
    districts: [
      "Merkez",
      "Beytüşşebap",
      "Cizre",
      "Güçlükonak",
      "İdil",
      "Silopi",
      "Uludere",
    ],
  },
  {
    name: "Tekirdağ",
    start: 948,
    num_of_districts: 11,
    districts: [
      "Çerkezköy",
      "Çorlu",
      "Ergene",
      "Hayrabolu",
      "Kapaklı",
      "Malkara",
      "Marmaraereğlisi",
      "Muratlı",
      "Saray / Tekirdağ",
      "Süleymanpaşa",
      "Şarköy",
    ],
  },
  {
    name: "Tokat",
    start: 960,
    num_of_districts: 12,
    districts: [
      "Merkez",
      "Almus",
      "Artova",
      "Başçiftlik",
      "Erbaa",
      "Niksar",
      "Pazar / Tokat",
      "Reşadiye",
      "Sulusaray",
      "Turhal",
      "Yeşilyurt / Tokat",
      "Zile",
    ],
  },
  {
    name: "Trabzon",
    start: 973,
    num_of_districts: 18,
    districts: [
      "Akçaabat",
      "Araklı",
      "Arsin",
      "Beşikdüzü",
      "Çarşıbaşı",
      "Çaykara",
      "Dernekpazarı",
      "Düzköy",
      "Hayrat",
      "Köprübaşı / Trabzon",
      "Maçka",
      "Of",
      "Ortahisar",
      "Sürmene",
      "Şalpazarı",
      "Tonya",
      "Vakfıkebir",
      "Yomra",
    ],
  },
  {
    name: "Tunceli",
    start: 992,
    num_of_districts: 8,
    districts: [
      "Merkez",
      "Çemişgezek",
      "Hozat",
      "Mazgirt",
      "Nazımiye",
      "Ovacık / Tunceli",
      "Pertek",
      "Pülümür",
    ],
  },
  {
    name: "Uşak",
    start: 1001,
    num_of_districts: 6,
    districts: [
      "Merkez",
      "Banaz",
      "Eşme",
      "Karahallı",
      "Sivaslı",
      "Ulubey / Uşak",
    ],
  },
  {
    name: "Yalova",
    start: 1008,
    num_of_districts: 6,
    districts: [
      "Merkez",
      "Altınova",
      "Armutlu",
      "Çınarcık",
      "Çiftlikköy",
      "Termal",
    ],
  },
  {
    name: "Van",
    start: 1015,
    num_of_districts: 13,
    districts: [
      "Bahçesaray",
      "Başkale",
      "Çaldıran",
      "Çatak",
      "Edremit / Van",
      "Erciş",
      "Gevaş",
      "Gürpınar",
      "İpekyolu",
      "Muradiye",
      "Özalp",
      "Saray / Van",
      "Tuşba",
    ],
  },
  {
    name: "Yozgat",
    start: 1029,
    num_of_districts: 14,
    districts: [
      "Merkez",
      "Akdağmadeni",
      "Aydıncık / Yozgat",
      "Boğazlıyan",
      "Çandır",
      "Çayıralan",
      "Çekerek",
      "Kadışehri",
      "Saraykent",
      "Sarıkaya",
      "Sorgun",
      "Şefaatli",
      "Yenifakılı",
      "Yerköy",
    ],
  },
  {
    name: "Zonguldak",
    start: 1044,
    num_of_districts: 8,
    districts: [
      "Merkez",
      "Alaplı",
      "Çaycuma",
      "Devrek",
      "Ereğli / Zonguldak",
      "Gökçebey",
      "Kilimli",
      "Kozlu",
    ],
  },
];
